version: 2

jobs:
  build-linux:
    docker:
      - image: nixos/nix:2.0
    working_directory: ~/rules_haskell
    resource_class: large
    steps:
      - checkout
      - run:
          name: System dependencies
          command: |
            apk --no-progress update
            apk --no-progress add bash ca-certificates
            nix-channel --update
      - run:
          name: Build
          command: |
            # XXX Workaround https://github.com/NixOS/nix/issues/1969.
            nix-build nixpkgs.nix -A haskell.compiler.ghc822
            # TODO Remove this once bazel-0.15 is merged in Nixpkgs.
            nix-build nixpkgs.nix -A bazel
            nix-shell --pure --run "bazel build --jobs=2 //... @haskell_zlib//..."
      - run:
          name: Run tests
          command: |
            # XXX Workaround https://github.com/NixOS/nix/issues/1969.
            nix-build '<nixpkgs>' -A haskell.compiler.ghc822
            nix-shell --pure --run "./run_tests.sh"

  build-darwin:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: Install Nix
          command: |
            curl https://nixos.org/nix/install | sh
      - run:
          name: System dependencies
          command: |
            brew update
            brew install bazel
            brew install go
      - run:
          name: Build
          shell: /bin/bash -eilo pipefail
          command: |
            nix-build ./tests/protoc_gen_haskell.nix
            bazel build --jobs=2 //...
      - run:
          name: Run tests
          shell: /bin/bash -eilo pipefail
          command: ./run_tests.sh

workflows:
  version: 2
  build:
    jobs:
      - build-linux
      - build-darwin
