version: 2

jobs:
  build-linux:
    docker:
      - image: nixos/nix
    working_directory: ~/rules_haskell
    steps:
      - checkout
      - run:
          name: System dependencies
          command: |
            apk --no-progress update
            apk --no-progress add bash ca-certificates
            nix-channel --update
            nix-env -iA nixpkgs.bazel nixpkgs.binutils nixpkgs.python
      - run:
          name: Build
          command: bazel build --jobs=2 //...
      - run:
          name: Run tests
          command: bazel test //... --config=ci
      - run:
          name: Test REPL for libraries
          command: bazel-bin/tests/haskell_repl/haskell_lib_repl -e ":quit"
      - run:
          name: Test REPL for binaries
          command: bazel-bin/tests/haskell_repl/haskell_bin_repl -e ":quit"
      - run:
          name: Test start script
          command: |
            pwd=$(pwd)
            cd $(mktemp -d)
            $pwd/start
            bazel fetch //... --config=ci

  build-darwin:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: Install Nix
          command: |
            curl https://nixos.org/nix/install | sh
      - run:
          name: System dependencies
          command: |
            brew update
            brew install bazel
      - run:
          name: Build
          shell: /bin/bash -eilo pipefail
          command: bazel build --jobs=2 //...
      - run:
          name: Run tests
          shell: /bin/bash -eilo pipefail
          command: bazel test //... --config=ci

workflows:
  version: 2
  build:
    jobs:
      - build-linux
      - build-darwin
